# Generated by Django 5.1.5 on 2025-03-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_likepost_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikePost',
        ),
    ]
