# Generated by Django 5.1.5 on 2026-01-16 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_e2ee_public_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_id', models.CharField(choices=[('first_post', 'First Post'), ('rising_star', 'Rising Star'), ('karma_king', 'Karma King'), ('week_warrior', 'Week Warrior'), ('community_builder', 'Community Builder'), ('social_butterfly', 'Social Butterfly')], max_length=50)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('shown_to_user', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement_id')},
            },
        ),
    ]
