# Generated by Django 5.1.5 on 2026-01-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_image_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos'),
        ),
    ]
