# Generated by Django 5.1.5 on 2026-01-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_public_id_slug'),
        ('blog', '0011_livestreamsignal'),
    ]

    operations = [
    ]
