# Generated by Django 5.1.5 on 2026-01-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_merge_0008_post_public_id_slug_0011_livestreamsignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this post has been viewed'),
        ),
        migrations.AlterField(
            model_name='livestreamsignal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
